<a href="https://colab.research.google.com/github/hursoo/big_k-modern_1/blob/main/gb_021_preprocess(big1).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 1.필요한 도구와 라이브러리 설치

In [1]:
# 구글 드라이브 마운트

from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [2]:
# 경로 지정

file_path = '/content/drive/MyDrive/big_km_history01/'

In [3]:
import pandas as pd
import numpy as np
import os
import sys
import re

# 2.데이터 불러오기

In [6]:
# 데이터 불러오기

df = pd.read_excel(file_path + 'result/ron10_data.xlsx') # gb_011...에서 저장한 파일
print(df.shape)

df

(10, 9)

,r_id,r_id_raw,title,writer,gisa_class,date,url,year,content
0,ma_013_0010_0020,ma_013_0010_0020,創刊辭,NaN,사고·편집후기,1920-06-25,http://db.history.go.kr/id/ma_013_0010_0020,1920,創刊辭\n소리-있어 넓히 世界에 傳하니 온 世界 모든 人類-이에 應하야 부르짖기를 ...
1,ma_013_0010_0030,ma_013_0010_0030,世界를 알라,NaN,논설,1920-06-25,http://db.history.go.kr/id/ma_013_0010_0030,1920,世界를 알라\n一\n사람은 天使도 안이며 野獸도 안이오 오즉 사람일 뿐이로다. 이만...
2,ma_013_0010_0060,ma_013_0010_0060,時急히 解決할 朝鮮의 二大問題,朴達成,논설,1920-06-25,http://db.history.go.kr/id/ma_013_0010_0060,1920,時急히 解決할 朝鮮의 二大問題\n朴達成\n남은 汽車를 타고 千里에 달아나는데 우리는...
3,ma_013_0020_0020,ma_013_0020_0020,"世界 三大 問題의 波及과 朝鮮人의 覺悟如何, 社說",NaN,논설,1920-07-25,http://db.history.go.kr/id/ma_013_0020_0020,1920,"世界 三大 問題의 波及과 朝鮮人의 覺悟如何, 社說\n1. 三大 問題는 그를 吸收하고..."
4,ma_013_0020_0040,ma_013_0020_0040,最近 朝鮮社會運動의 二三,李敦化,논설,1920-07-25,http://db.history.go.kr/id/ma_013_0020_0040,1920,"最近 朝鮮社會運動의 二三\n李敦化\n朝鮮敎育會, 朝鮮學生大會, 朝鮮勞働共濟會의 趣旨..."
5,ma_013_0020_0050,ma_013_0020_0050,"急激히 向上되는 朝鮮靑年의 思想界, 可賀할 朝鮮靑年의 知識熱",朴達成,논설,1920-07-25,http://db.history.go.kr/id/ma_013_0020_0050,1920,"急激히 向上되는 朝鮮靑年의 思想界, 可賀할 朝鮮靑年의 知識熱\n朴達成\n無私한 태양..."
6,ma_013_0030_0020,ma_013_0030_0020,吾人의 新紀元을 宣言하노라,NaN,논설,1920-08-25,http://db.history.go.kr/id/ma_013_0030_0020,1920,吾人의 新紀元을 宣言하노라\n吾人은 均히 自國 歷史의 長遠을 자랑하고 自家譜乘의 久...
7,ma_013_0030_0030,ma_013_0030_0030,新時代와 新人物,NaN,논설,1920-08-25,http://db.history.go.kr/id/ma_013_0030_0030,1920,新時代와 新人物\n一. 改造라 함은 人類의 靈力이 自然의 上에 作用함을 이름이라\n...
8,ma_013_0030_0050,ma_013_0030_0050,家族制度의 側面觀,滄海居士,논설,1920-08-25,http://db.history.go.kr/id/ma_013_0030_0050,1920,家族制度의 側面觀\n滄海居士\n一. 家族制度의 變遷\n家族制度에도 美點이 업는 바 ...
9,ma_013_0030_0070,ma_013_0030_0070,朝鮮女子의 今後行路,妙香山人,논설,1920-08-25,http://db.history.go.kr/id/ma_013_0030_0070,1920,朝鮮女子의 今後行路\n妙香山人\n누의님 悾惚한 이 歲月이 일만흔 우리에게 더욱 悾惚...

In [8]:
# 일부 필요한 열만 출력

df1 = df[['r_id', 'title', 'content']]
df1

,r_id,title,content
0,ma_013_0010_0020,創刊辭,創刊辭\n소리-있어 넓히 世界에 傳하니 온 世界 모든 人類-이에 應하야 부르짖기를 ...
1,ma_013_0010_0030,世界를 알라,世界를 알라\n一\n사람은 天使도 안이며 野獸도 안이오 오즉 사람일 뿐이로다. 이만...
2,ma_013_0010_0060,時急히 解決할 朝鮮의 二大問題,時急히 解決할 朝鮮의 二大問題\n朴達成\n남은 汽車를 타고 千里에 달아나는데 우리는...
3,ma_013_0020_0020,"世界 三大 問題의 波及과 朝鮮人의 覺悟如何, 社說","世界 三大 問題의 波及과 朝鮮人의 覺悟如何, 社說\n1. 三大 問題는 그를 吸收하고..."
4,ma_013_0020_0040,最近 朝鮮社會運動의 二三,"最近 朝鮮社會運動의 二三\n李敦化\n朝鮮敎育會, 朝鮮學生大會, 朝鮮勞働共濟會의 趣旨..."
5,ma_013_0020_0050,"急激히 向上되는 朝鮮靑年의 思想界, 可賀할 朝鮮靑年의 知識熱","急激히 向上되는 朝鮮靑年의 思想界, 可賀할 朝鮮靑年의 知識熱\n朴達成\n無私한 태양..."
6,ma_013_0030_0020,吾人의 新紀元을 宣言하노라,吾人의 新紀元을 宣言하노라\n吾人은 均히 自國 歷史의 長遠을 자랑하고 自家譜乘의 久...
7,ma_013_0030_0030,新時代와 新人物,新時代와 新人物\n一. 改造라 함은 人類의 靈力이 自然의 上에 作用함을 이름이라\n...
8,ma_013_0030_0050,家族制度의 側面觀,家族制度의 側面觀\n滄海居士\n一. 家族制度의 變遷\n家族制度에도 美點이 업는 바 ...
9,ma_013_0030_0070,朝鮮女子의 今後行路,朝鮮女子의 今後行路\n妙香山人\n누의님 悾惚한 이 歲月이 일만흔 우리에게 더욱 悾惚...

# 3.기사를 문장별로 분리

In [9]:
import re

# raw string 사용
separators = [r'\n', r'\.', r'!', r'\?']
pattern = '|'.join(separators)  # 바로 윗 줄 구분자들을 '또는'으로 연결함

df1 = df1.copy()
df1.loc[:, 'splited_sent'] = df1['content'].apply(lambda x: re.split(pattern, x))
df1

,r_id,title,content,splited_sent
0,ma_013_0010_0020,創刊辭,創刊辭\n소리-있어 넓히 世界에 傳하니 온 世界 모든 人類-이에 應하야 부르짖기를 ...,"[創刊辭, 소리-있어 넓히 世界에 傳하니 온 世界 모든 人類-이에 應하야 부르짖기를..."
1,ma_013_0010_0030,世界를 알라,世界를 알라\n一\n사람은 天使도 안이며 野獸도 안이오 오즉 사람일 뿐이로다. 이만...,"[世界를 알라, 一, 사람은 天使도 안이며 野獸도 안이오 오즉 사람일 뿐이로다, ..."
2,ma_013_0010_0060,時急히 解決할 朝鮮의 二大問題,時急히 解決할 朝鮮의 二大問題\n朴達成\n남은 汽車를 타고 千里에 달아나는데 우리는...,"[時急히 解決할 朝鮮의 二大問題, 朴達成, 남은 汽車를 타고 千里에 달아나는데 우리..."
3,ma_013_0020_0020,"世界 三大 問題의 波及과 朝鮮人의 覺悟如何, 社說","世界 三大 問題의 波及과 朝鮮人의 覺悟如何, 社說\n1. 三大 問題는 그를 吸收하고...","[世界 三大 問題의 波及과 朝鮮人의 覺悟如何, 社說, 1, 三大 問題는 그를 吸收..."
4,ma_013_0020_0040,最近 朝鮮社會運動의 二三,"最近 朝鮮社會運動의 二三\n李敦化\n朝鮮敎育會, 朝鮮學生大會, 朝鮮勞働共濟會의 趣旨...","[最近 朝鮮社會運動의 二三, 李敦化, 朝鮮敎育會, 朝鮮學生大會, 朝鮮勞働共濟會의 趣..."
5,ma_013_0020_0050,"急激히 向上되는 朝鮮靑年의 思想界, 可賀할 朝鮮靑年의 知識熱","急激히 向上되는 朝鮮靑年의 思想界, 可賀할 朝鮮靑年의 知識熱\n朴達成\n無私한 태양...","[急激히 向上되는 朝鮮靑年의 思想界, 可賀할 朝鮮靑年의 知識熱, 朴達成, 無私한 태..."
6,ma_013_0030_0020,吾人의 新紀元을 宣言하노라,吾人의 新紀元을 宣言하노라\n吾人은 均히 自國 歷史의 長遠을 자랑하고 自家譜乘의 久...,"[吾人의 新紀元을 宣言하노라, 吾人은 均히 自國 歷史의 長遠을 자랑하고 自家譜乘의 ..."
7,ma_013_0030_0030,新時代와 新人物,新時代와 新人物\n一. 改造라 함은 人類의 靈力이 自然의 上에 作用함을 이름이라\n...,"[新時代와 新人物, 一, 改造라 함은 人類의 靈力이 自然의 上에 作用함을 이름이라..."
8,ma_013_0030_0050,家族制度의 側面觀,家族制度의 側面觀\n滄海居士\n一. 家族制度의 變遷\n家族制度에도 美點이 업는 바 ...,"[家族制度의 側面觀, 滄海居士, 一, 家族制度의 變遷, 家族制度에도 美點이 업는 ..."
9,ma_013_0030_0070,朝鮮女子의 今後行路,朝鮮女子의 今後行路\n妙香山人\n누의님 悾惚한 이 歲月이 일만흔 우리에게 더욱 悾惚...,"[朝鮮女子의 今後行路, 妙香山人, 누의님 悾惚한 이 歲月이 일만흔 우리에게 더욱 悾..."

In [10]:
# 각 문장을 df의 행이 되도록 변환

sents_df = df1.explode('splited_sent')
sents_df = sents_df.reset_index(drop=True) # 인덱스를 재부여
sents_df

,r_id,title,content,splited_sent
0,ma_013_0010_0020,創刊辭,創刊辭\n소리-있어 넓히 世界에 傳하니 온 世界 모든 人類-이에 應하야 부르짖기를 ...,創刊辭
1,ma_013_0010_0020,創刊辭,創刊辭\n소리-있어 넓히 世界에 傳하니 온 世界 모든 人類-이에 應하야 부르짖기를 ...,소리-있어 넓히 世界에 傳하니 온 世界 모든 人類-이에 應하야 부르짖기를 始作하도다
2,ma_013_0010_0020,創刊辭,創刊辭\n소리-있어 넓히 世界에 傳하니 온 世界 모든 人類-이에 應하야 부르짖기를 ...,强者도 부르짖고 弱者도 부르짖으며 優者도 부르짖고 劣者도 부르짖도다
3,ma_013_0010_0020,創刊辭,創刊辭\n소리-있어 넓히 世界에 傳하니 온 世界 모든 人類-이에 應하야 부르짖기를 ...,"東西南北, 四海八方이 다같이 소리中에 묻혀 있도다"
4,ma_013_0010_0020,創刊辭,創刊辭\n소리-있어 넓히 世界에 傳하니 온 世界 모든 人類-이에 應하야 부르짖기를 ...,霹靂이냐 地震이냐 神籟이냐 魔哭이냐 우리는 아즉이 소리의 正邪를 判斷할 수 없도다
...,...,...,...,...
1317,ma_013_0030_0070,朝鮮女子의 今後行路,朝鮮女子의 今後行路\n妙香山人\n누의님 悾惚한 이 歲月이 일만흔 우리에게 더욱 悾惚...,그러나 저는 모르나이다
1318,ma_013_0030_0070,朝鮮女子의 今後行路,朝鮮女子의 今後行路\n妙香山人\n누의님 悾惚한 이 歲月이 일만흔 우리에게 더욱 悾惚...,다못 이 글을 올리는 이때에 느끼는 것을 그대로 적엇슬 뿐이외다
1319,ma_013_0030_0070,朝鮮女子의 今後行路,朝鮮女子의 今後行路\n妙香山人\n누의님 悾惚한 이 歲月이 일만흔 우리에게 더욱 悾惚...,틈을 어더 이에 對한 제의 所見을 具體的으로 말삼할 것을 豫期하오며 爲先 누의님의...
1320,ma_013_0030_0070,朝鮮女子의 今後行路,朝鮮女子의 今後行路\n妙香山人\n누의님 悾惚한 이 歲月이 일만흔 우리에게 더욱 悾惚...,
1321,ma_013_0030_0070,朝鮮女子의 今後行路,朝鮮女子의 今後行路\n妙香山人\n누의님 悾惚한 이 歲月이 일만흔 우리에게 더욱 悾惚...,(이만) ＜29-33＞

# 4.형태소 분석
- 제목: 형태소 분석기 적용
- kiwi 형태소 분석기로 텍스트 데이터 분석

## 4.1.kiwi 설치

In [11]:
# kiwi 설치
!pip install -U kiwipiepy

Collecting kiwipiepy
  Downloading kiwipiepy-0.21.0-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (1.3 kB)
Collecting kiwipiepy_model<0.22,>=0.21 (from kiwipiepy)
  Downloading kiwipiepy_model-0.21.0.tar.gz (35.5 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 35.5/35.5 MB 30.3 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Requirement already satisfied: numpy in /usr/local/lib/python3.11/dist-packages (from kiwipiepy) (2.0.2)
Requirement already satisfied: tqdm in /usr/local/lib/python3.11/dist-packages (from kiwipiepy) (4.67.1)
Downloading kiwipiepy-0.21.0-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (7.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.6/7.6 MB 36.8 MB/s eta 0:00:00
Building wheels for collected packages: kiwipiepy_model
  Building wheel for kiwipiepy_model (setup.py) ... done
  Created wheel for kiwipiepy_model: filename=kiwipiepy_model-0.21.0-py3-none-any.whl size=35593192 sha256=254a832b72af1c8001c0fb9eb9e03ba56759aad709eec94a3a43274de98b2560
  Stored in directory: /root/.cache/pip/wheels/b0/16/3d/95053ab5298f0f0f22ffea6de0200b6f24bffb73cab4c1a828
Successfully built kiwipiepy_model
Installing collected packages: kiwipiepy_model, kiwipiepy
Successfully installed kiwipiepy-0.21.0 kiwipiepy_model-0.21.0

## 4.2.형태소 분석 함수 작성

In [12]:
from kiwipiepy import Kiwi

# Kiwi 객체 생성
kiwi = Kiwi()

# 텍스트 분석
text = "소리-있어 넓히 世界에 傳하니 온 世界 모든 人類-이에 應하야 부르짖기를 始作하도다"
results = kiwi.analyze(text)

results

[([Token(form='소리', tag='NNG', start=0, len=2),
   Token(form='-', tag='SO', start=2, len=1),
   Token(form='있', tag='VV', start=3, len=1),
   Token(form='어', tag='EC', start=4, len=1),
   Token(form='넓히', tag='VV', start=6, len=2),
   Token(form='世界', tag='SH', start=9, len=2),
   Token(form='에', tag='JKB', start=11, len=1),
   Token(form='傳', tag='SH', start=13, len=1),
   Token(form='하', tag='VV', start=14, len=1),
   Token(form='니', tag='EC', start=15, len=1),
   Token(form='오', tag='VX', start=17, len=1),
   Token(form='ᆫ', tag='ETM', start=17, len=1),
   Token(form='世界', tag='SH', start=19, len=2),
   Token(form='모', tag='NP', start=22, len=1),
   Token(form='이', tag='VCP', start=23, len=0),
   Token(form='든', tag='EC', start=23, len=1),
   Token(form='人類', tag='SH', start=25, len=2),
   Token(form='-', tag='SO', start=27, len=1),
   Token(form='이', tag='NNG', start=28, len=1),
   Token(form='에', tag='JKB', start=29, len=1),
   Token(form='應', tag='SH', start=31, len=1),
   Token(form='하', tag='XSV', start=32, len=1),
   Token(form='야', tag='EC', start=33, len=1),
   Token(form='부르짖', tag='VV', start=35, len=3),
   Token(form='기', tag='ETN', start=38, len=1),
   Token(form='를', tag='JKO', start=39, len=1),
   Token(form='始作', tag='SH', start=41, len=2),
   Token(form='하', tag='XSV', start=43, len=1),
   Token(form='도다', tag='EF', start=44, len=2)],
  -204.94419860839844)]

In [13]:
# 영어, 숫자, 특정 부호 등 제외하기
def filter_elements(lst):
    # 영어, 숫자 및 '<' 문자만을 허용하는 정규식 패턴
    pattern = re.compile(r'^[a-zA-Z0-9<＞「」]+$')

    # 해당 패턴과 일치하지 않는 문자열만을 반환하는 필터링 함수
    return list(filter(lambda x: not pattern.match(x), lst))

# 형태소 분석 결과를 단순한 형태로 출력하는 사용자 함수
def simplify_kiwi(sent):
    morphed_list = []
    results = kiwi.analyze(sent)
    for result in results:
        for token in result[0]:  # result는 (token_list, int) 형태의 튜플입니다.
            morphed = (token.form + "/" + token.tag)  # 각 토큰의 형태소와 품사 태그 출력
            morphed_list.append(morphed)
    return morphed_list

# 본격 형태소 분석
import string
def do_morph(sent):
    # 토큰나이징 결과 확인 (subword + 한국어 형태소)
    vocab_list = simplify_kiwi(sent)
    result01 = filter_elements(vocab_list) # 영어, 숫자, 특정부호 제외 (사용자 함수)
    return result01

## 4.3.형태소 분석 및 정리 정돈

In [14]:
print(sents_df.shape)
sents_df.head(5)

(1322, 4)

,r_id,title,content,splited_sent
0,ma_013_0010_0020,創刊辭,創刊辭\n소리-있어 넓히 世界에 傳하니 온 世界 모든 人類-이에 應하야 부르짖기를 ...,創刊辭
1,ma_013_0010_0020,創刊辭,創刊辭\n소리-있어 넓히 世界에 傳하니 온 世界 모든 人類-이에 應하야 부르짖기를 ...,소리-있어 넓히 世界에 傳하니 온 世界 모든 人類-이에 應하야 부르짖기를 始作하도다
2,ma_013_0010_0020,創刊辭,創刊辭\n소리-있어 넓히 世界에 傳하니 온 世界 모든 人類-이에 應하야 부르짖기를 ...,强者도 부르짖고 弱者도 부르짖으며 優者도 부르짖고 劣者도 부르짖도다
3,ma_013_0010_0020,創刊辭,創刊辭\n소리-있어 넓히 世界에 傳하니 온 世界 모든 人類-이에 應하야 부르짖기를 ...,"東西南北, 四海八方이 다같이 소리中에 묻혀 있도다"
4,ma_013_0010_0020,創刊辭,創刊辭\n소리-있어 넓히 世界에 傳하니 온 世界 모든 人類-이에 應하야 부르짖기를 ...,霹靂이냐 地震이냐 神籟이냐 魔哭이냐 우리는 아즉이 소리의 正邪를 判斷할 수 없도다

In [15]:
# 'content' 열에 kiwi 형태소 분석기 적용
sents_df = sents_df.copy()
sents_df['tokens'] = sents_df['splited_sent'].apply(do_morph)
sents_df

,r_id,title,content,splited_sent,tokens
0,ma_013_0010_0020,創刊辭,創刊辭\n소리-있어 넓히 世界에 傳하니 온 世界 모든 人類-이에 應하야 부르짖기를 ...,創刊辭,[創刊辭/SH]
1,ma_013_0010_0020,創刊辭,創刊辭\n소리-있어 넓히 世界에 傳하니 온 世界 모든 人類-이에 應하야 부르짖기를 ...,소리-있어 넓히 世界에 傳하니 온 世界 모든 人類-이에 應하야 부르짖기를 始作하도다,"[소리/NNG, -/SO, 있/VV, 어/EC, 넓히/VV, 世界/SH, 에/JKB..."
2,ma_013_0010_0020,創刊辭,創刊辭\n소리-있어 넓히 世界에 傳하니 온 世界 모든 人類-이에 應하야 부르짖기를 ...,强者도 부르짖고 弱者도 부르짖으며 優者도 부르짖고 劣者도 부르짖도다,"[强者/SH, 도/JX, 부르짖/VV, 고/EC, 弱者/SH, 도/JX, 부르짖/V..."
3,ma_013_0010_0020,創刊辭,創刊辭\n소리-있어 넓히 世界에 傳하니 온 世界 모든 人類-이에 應하야 부르짖기를 ...,"東西南北, 四海八方이 다같이 소리中에 묻혀 있도다","[東西南北/SH, ,/SP, 四海八方/SH, 이/JKS, 다/MAG, 같이/MAG,..."
4,ma_013_0010_0020,創刊辭,創刊辭\n소리-있어 넓히 世界에 傳하니 온 世界 모든 人類-이에 應하야 부르짖기를 ...,霹靂이냐 地震이냐 神籟이냐 魔哭이냐 우리는 아즉이 소리의 正邪를 判斷할 수 없도다,"[霹靂/SH, 이냐/NNG, 地震/SH, 이/VCP, 냐/EC, 神籟/SH, 이/V..."
...,...,...,...,...,...
1317,ma_013_0030_0070,朝鮮女子의 今後行路,朝鮮女子의 今後行路\n妙香山人\n누의님 悾惚한 이 歲月이 일만흔 우리에게 더욱 悾惚...,그러나 저는 모르나이다,"[그러나/MAJ, 저/NP, 는/JX, 모르/VV, 나/EC, 이/VCP, 다/EF]"
1318,ma_013_0030_0070,朝鮮女子의 今後行路,朝鮮女子의 今後行路\n妙香山人\n누의님 悾惚한 이 歲月이 일만흔 우리에게 더욱 悾惚...,다못 이 글을 올리는 이때에 느끼는 것을 그대로 적엇슬 뿐이외다,"[다/MAG, 못/MAG, 이/MM, 글/NNG, 을/JKO, 올리/VV, 는/ET..."
1319,ma_013_0030_0070,朝鮮女子의 今後行路,朝鮮女子의 今後行路\n妙香山人\n누의님 悾惚한 이 歲月이 일만흔 우리에게 더욱 悾惚...,틈을 어더 이에 對한 제의 所見을 具體的으로 말삼할 것을 豫期하오며 爲先 누의님의...,"[틈/NNG, 을/JKO, 어/IC, 더/MAG, 이/NP, 에/JKB, 對/SH,..."
1320,ma_013_0030_0070,朝鮮女子의 今後行路,朝鮮女子의 今後行路\n妙香山人\n누의님 悾惚한 이 歲月이 일만흔 우리에게 더욱 悾惚...,,[]
1321,ma_013_0030_0070,朝鮮女子의 今後行路,朝鮮女子의 今後行路\n妙香山人\n누의님 悾惚한 이 歲月이 일만흔 우리에게 더욱 悾惚...,(이만) ＜29-33＞,"[(/SSO, 이만/MAG, )/SSC, ＜/SSO, 29-33/W_SERIAL, ..."

In [16]:
# 'tokens' 열에서 리스트 요소가 하나도 없는 행 제거
sents_df1 = sents_df[sents_df['tokens'].str.len() > 0]

sents_df1 = sents_df1.copy()
sents_df1['tokens'] = sents_df1['tokens'].apply(lambda x: ' '.join(x)) # 리스트를 문자열로
sents_df1

,r_id,title,content,splited_sent,tokens
0,ma_013_0010_0020,創刊辭,創刊辭\n소리-있어 넓히 世界에 傳하니 온 世界 모든 人類-이에 應하야 부르짖기를 ...,創刊辭,創刊辭/SH
1,ma_013_0010_0020,創刊辭,創刊辭\n소리-있어 넓히 世界에 傳하니 온 世界 모든 人類-이에 應하야 부르짖기를 ...,소리-있어 넓히 世界에 傳하니 온 世界 모든 人類-이에 應하야 부르짖기를 始作하도다,소리/NNG -/SO 있/VV 어/EC 넓히/VV 世界/SH 에/JKB 傳/SH 하...
2,ma_013_0010_0020,創刊辭,創刊辭\n소리-있어 넓히 世界에 傳하니 온 世界 모든 人類-이에 應하야 부르짖기를 ...,强者도 부르짖고 弱者도 부르짖으며 優者도 부르짖고 劣者도 부르짖도다,强者/SH 도/JX 부르짖/VV 고/EC 弱者/SH 도/JX 부르짖/VV 으며/EC...
3,ma_013_0010_0020,創刊辭,創刊辭\n소리-있어 넓히 世界에 傳하니 온 世界 모든 人類-이에 應하야 부르짖기를 ...,"東西南北, 四海八方이 다같이 소리中에 묻혀 있도다","東西南北/SH ,/SP 四海八方/SH 이/JKS 다/MAG 같이/MAG 소리/NNG..."
4,ma_013_0010_0020,創刊辭,創刊辭\n소리-있어 넓히 世界에 傳하니 온 世界 모든 人類-이에 應하야 부르짖기를 ...,霹靂이냐 地震이냐 神籟이냐 魔哭이냐 우리는 아즉이 소리의 正邪를 判斷할 수 없도다,霹靂/SH 이냐/NNG 地震/SH 이/VCP 냐/EC 神籟/SH 이/VCP 냐/EC...
...,...,...,...,...,...
1316,ma_013_0030_0070,朝鮮女子의 今後行路,朝鮮女子의 今後行路\n妙香山人\n누의님 悾惚한 이 歲月이 일만흔 우리에게 더욱 悾惚...,그런 中에도 말이 아모 脈絡이 업고 成筭이 업는 말할 수 업는 粗笨이외다,그런/MM 中/SH 에/JKB 도/JX 말/NNG 이/JKS 아모/NNG 脈絡/SH...
1317,ma_013_0030_0070,朝鮮女子의 今後行路,朝鮮女子의 今後行路\n妙香山人\n누의님 悾惚한 이 歲月이 일만흔 우리에게 더욱 悾惚...,그러나 저는 모르나이다,그러나/MAJ 저/NP 는/JX 모르/VV 나/EC 이/VCP 다/EF
1318,ma_013_0030_0070,朝鮮女子의 今後行路,朝鮮女子의 今後行路\n妙香山人\n누의님 悾惚한 이 歲月이 일만흔 우리에게 더욱 悾惚...,다못 이 글을 올리는 이때에 느끼는 것을 그대로 적엇슬 뿐이외다,다/MAG 못/MAG 이/MM 글/NNG 을/JKO 올리/VV 는/ETM 이때/NN...
1319,ma_013_0030_0070,朝鮮女子의 今後行路,朝鮮女子의 今後行路\n妙香山人\n누의님 悾惚한 이 歲月이 일만흔 우리에게 더욱 悾惚...,틈을 어더 이에 對한 제의 所見을 具體的으로 말삼할 것을 豫期하오며 爲先 누의님의...,틈/NNG 을/JKO 어/IC 더/MAG 이/NP 에/JKB 對/SH 하/XSV ᆫ...
1321,ma_013_0030_0070,朝鮮女子의 今後行路,朝鮮女子의 今後行路\n妙香山人\n누의님 悾惚한 이 歲月이 일만흔 우리에게 더욱 悾惚...,(이만) ＜29-33＞,(/SSO 이만/MAG )/SSC ＜/SSO 29-33/W_SERIAL ＞/SSC

In [17]:
sents_df1['morph'] = sents_df1['tokens'].apply(
    lambda x: [token.split('/')[0] for token in x.split() if token.split('/')[-1] in ['SH', 'NP', 'NNP']]
)

# 'morph' 열에서 리스트 요소가 하나도 없는 행 제거
sents_df2 = sents_df1[sents_df1['morph'].str.len() > 0]

# 리스트를 문자열로
sents_df2 = sents_df2.copy()
sents_df2['morph'] = sents_df2['morph'].apply(lambda x: ' '.join(x))

print(sents_df2.shape)
sents_df2.head(5)

(1082, 6)

,r_id,title,content,splited_sent,tokens,morph
0,ma_013_0010_0020,創刊辭,創刊辭\n소리-있어 넓히 世界에 傳하니 온 世界 모든 人類-이에 應하야 부르짖기를 ...,創刊辭,創刊辭/SH,創刊辭
1,ma_013_0010_0020,創刊辭,創刊辭\n소리-있어 넓히 世界에 傳하니 온 世界 모든 人類-이에 應하야 부르짖기를 ...,소리-있어 넓히 世界에 傳하니 온 世界 모든 人類-이에 應하야 부르짖기를 始作하도다,소리/NNG -/SO 있/VV 어/EC 넓히/VV 世界/SH 에/JKB 傳/SH 하...,世界 傳 世界 모 人類 應 始作
2,ma_013_0010_0020,創刊辭,創刊辭\n소리-있어 넓히 世界에 傳하니 온 世界 모든 人類-이에 應하야 부르짖기를 ...,强者도 부르짖고 弱者도 부르짖으며 優者도 부르짖고 劣者도 부르짖도다,强者/SH 도/JX 부르짖/VV 고/EC 弱者/SH 도/JX 부르짖/VV 으며/EC...,强者 弱者 優者 劣者
3,ma_013_0010_0020,創刊辭,創刊辭\n소리-있어 넓히 世界에 傳하니 온 世界 모든 人類-이에 應하야 부르짖기를 ...,"東西南北, 四海八方이 다같이 소리中에 묻혀 있도다","東西南北/SH ,/SP 四海八方/SH 이/JKS 다/MAG 같이/MAG 소리/NNG...",東西南北 四海八方 中
4,ma_013_0010_0020,創刊辭,創刊辭\n소리-있어 넓히 世界에 傳하니 온 世界 모든 人類-이에 應하야 부르짖기를 ...,霹靂이냐 地震이냐 神籟이냐 魔哭이냐 우리는 아즉이 소리의 正邪를 判斷할 수 없도다,霹靂/SH 이냐/NNG 地震/SH 이/VCP 냐/EC 神籟/SH 이/VCP 냐/EC...,霹靂 地震 神籟 魔哭 우리 正邪 判斷

In [18]:
# 문장 인덱스 생성
sents_df2 = sents_df2.reset_index(drop = True)
sents_df2['sent_id'] = sents_df2.index + 1

# 열 순서 변경
sents = sents_df2[['sent_id', 'morph', 'splited_sent', 'r_id', 'title', 'content']]
sents

,sent_id,morph,splited_sent,r_id,title,content
0,1,創刊辭,創刊辭,ma_013_0010_0020,創刊辭,創刊辭\n소리-있어 넓히 世界에 傳하니 온 世界 모든 人類-이에 應하야 부르짖기를 ...
1,2,世界 傳 世界 모 人類 應 始作,소리-있어 넓히 世界에 傳하니 온 世界 모든 人類-이에 應하야 부르짖기를 始作하도다,ma_013_0010_0020,創刊辭,創刊辭\n소리-있어 넓히 世界에 傳하니 온 世界 모든 人類-이에 應하야 부르짖기를 ...
2,3,强者 弱者 優者 劣者,强者도 부르짖고 弱者도 부르짖으며 優者도 부르짖고 劣者도 부르짖도다,ma_013_0010_0020,創刊辭,創刊辭\n소리-있어 넓히 世界에 傳하니 온 世界 모든 人類-이에 應하야 부르짖기를 ...
3,4,東西南北 四海八方 中,"東西南北, 四海八方이 다같이 소리中에 묻혀 있도다",ma_013_0010_0020,創刊辭,創刊辭\n소리-있어 넓히 世界에 傳하니 온 世界 모든 人類-이에 應하야 부르짖기를 ...
4,5,霹靂 地震 神籟 魔哭 우리 正邪 判斷,霹靂이냐 地震이냐 神籟이냐 魔哭이냐 우리는 아즉이 소리의 正邪를 判斷할 수 없도다,ma_013_0010_0020,創刊辭,創刊辭\n소리-있어 넓히 世界에 傳하니 온 世界 모든 人類-이에 應하야 부르짖기를 ...
...,...,...,...,...,...,...
1077,1078,其他 무엇 무엇 爲先 近 遠 淺 深 入 如 順序的 着實 進 連方 實 結 過渡期 脫 ...,其他 무엇무엇이던지 爲先 近에서 遠에 淺에서 深에 入함과 如히 順序的으로 着實히 ...,ma_013_0030_0070,朝鮮女子의 今後行路,朝鮮女子의 今後行路\n妙香山人\n누의님 悾惚한 이 歲月이 일만흔 우리에게 더욱 悾惚...
1078,1079,片紙,누의님 片紙가 넘우 길어젓슴니다,ma_013_0030_0070,朝鮮女子의 今後行路,朝鮮女子의 今後行路\n妙香山人\n누의님 悾惚한 이 歲月이 일만흔 우리에게 더욱 悾惚...
1079,1080,中 脈絡 成筭 粗笨,그런 中에도 말이 아모 脈絡이 업고 成筭이 업는 말할 수 업는 粗笨이외다,ma_013_0030_0070,朝鮮女子의 今後行路,朝鮮女子의 今後行路\n妙香山人\n누의님 悾惚한 이 歲月이 일만흔 우리에게 더욱 悾惚...
1080,1081,저,그러나 저는 모르나이다,ma_013_0030_0070,朝鮮女子의 今後行路,朝鮮女子의 今後行路\n妙香山人\n누의님 悾惚한 이 歲月이 일만흔 우리에게 더욱 悾惚...
1081,1082,이 對 所見 具體的 豫期 爲先 斯界 對 獨特 意見 敢仰,틈을 어더 이에 對한 제의 所見을 具體的으로 말삼할 것을 豫期하오며 爲先 누의님의...,ma_013_0030_0070,朝鮮女子의 今後行路,朝鮮女子의 今後行路\n妙香山人\n누의님 悾惚한 이 歲月이 일만흔 우리에게 더욱 悾惚...

# The End of Notebook